Run_AI_Rank: 'False'
Run_Search: 'True'
Run_WebApp: 'True'
ai_model: gpt-4o-mini
ai_rank: 'True'
config_directory: configs
config_modelname: QuantumOptics
host: OpenAI
lookback_date: '14'
output_db: 'False'
output_directory: ./articles
output_md: 'True'
output_pdf: ./articles/pdf
print_articles: 'False'
save_articles: 'True'
search_abstract: 'True'
search_authors: 'False'
search_title: 'True'
